/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect;

/**
 *
 * @author Antoo
 */
public class Initialization extends javax.swing.JFrame {
    private static int i =0;

    /**
     * Creates new form NewJFrame
     */
    public Initialization() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Supplier = new javax.swing.JButton();
        show_customer = new javax.swing.JButton();
        show_products = new javax.swing.JButton();
        Category = new javax.swing.JButton();
        add_products = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Supplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Supplier.setIcon(new javax.swing.ImageIcon("C:\\Users\\ankur\\OneDrive\\Documents\\NetBeansProjects\\Connect\\icons\\icons8-supplier-50.png")); // NOI18N
        Supplier.setText("Supplier");
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });

        show_customer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        show_customer.setIcon(new javax.swing.ImageIcon("C:\\Users\\ankur\\OneDrive\\Documents\\NetBeansProjects\\Connect\\icons\\icons8-purchase-order-50.png")); // NOI18N
        show_customer.setText("Show Customer");
        show_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_customerActionPerformed(evt);
            }
        });

        show_products.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        show_products.setText("Show Prdoucts");
        show_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_productsMouseClicked(evt);
            }
        });
        show_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_productsActionPerformed(evt);
            }
        });

        Category.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Category.setIcon(new javax.swing.ImageIcon("C:\\Users\\ankur\\OneDrive\\Documents\\NetBeansProjects\\Connect\\icons\\icons8-category-30.png")); // NOI18N
        Category.setText("Add Category");
        Category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryMouseClicked(evt);
            }
        });
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });

        add_products.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_products.setIcon(new javax.swing.ImageIcon("C:\\Users\\ankur\\OneDrive\\Documents\\NetBeansProjects\\Connect\\icons\\icons8-grocery-shelf-50.png")); // NOI18N
        add_products.setText("Add Products");
        add_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_productsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show_products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Supplier)
                .addGap(18, 18, 18)
                .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(add_products)
                .addGap(27, 27, 27)
                .addComponent(show_products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(show_customer)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
//                 TODO add your handling code here:
//                  ConnectMSSQL con= new ConnectMSSQL();
//                  con.show_customer();
                  
                  Supplier f=new Supplier();
                  f.show_supplier();
                  f.setVisible(true);                
                  dispose();
    }//GEN-LAST:event_SupplierActionPerformed

    private void show_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_customerActionPerformed
        // TODO add your handling code here:
        Add_Category c= new Add_Category();
        Products p= new Products();
        c.names.clear();
        p.names.clear();
        Customer customer= new Customer();
        customer.setVisible(true);
        customer.show_customer();
        c.Show_category2();
        p.show_prot();
        customer.add_Category();
        customer.add_Product();
       
        dispose();
    }//GEN-LAST:event_show_customerActionPerformed

    private void show_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_productsActionPerformed
        // TODO add your handling code here:
         Supplier s= new Supplier();
         Add_Category c= new Add_Category();
        s.names.clear();
        c.names.clear();
        Products product= new Products();
        product.show_prot();
//        product.show_categorywise_order();
        s.show_supplier();
        c.Show_category2();
        product.addItem();
        product.add_Category();
            
        
        
        product.setVisible(true);
        dispose();
    }//GEN-LAST:event_show_productsActionPerformed

    private void CategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryMouseClicked
        // TODO add your handling code here:
        Add_Category category= new Add_Category();
        category.Show_category();
        category.setVisible(true);
        dispose();
    }//GEN-LAST:event_CategoryMouseClicked

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryActionPerformed

    private void add_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_productsMouseClicked
        // TODO add your handling code here:
        Add_product product= new Add_product();
        product.setVisible(true);
        product.show_product();
        dispose();
    }//GEN-LAST:event_add_productsMouseClicked

    private void show_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_productsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_show_productsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Initialization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Initialization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Initialization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Initialization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Initialization().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Category;
    private javax.swing.JButton Supplier;
    private javax.swing.JButton add_products;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton show_customer;
    private javax.swing.JButton show_products;
    // End of variables declaration//GEN-END:variables
}
