/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect;

import static connect.Supplier.names;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Antoo
 */
public class Supplier extends javax.swing.JFrame {
    
   public static ArrayList<String> names = new ArrayList<String>();
   
   public  void Addname(String Name){

   names.add(Name);

       
   }
   
  
  
    /**
     * Creates new form NewJFrame2
     */
    public Supplier() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Go_Back = new javax.swing.JButton();
        supplier_id = new javax.swing.JLabel();
        jt_sid = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        jt_name = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        jt_address = new javax.swing.JTextField();
        Insert = new javax.swing.JButton();
        jt_phone = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        jt_fax = new javax.swing.JTextField();
        fax = new javax.swing.JLabel();
        jt_email = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        jt_other_details = new javax.swing.JTextField();
        other_details = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sid", "Name", "Address", "Phone", "Fax", "Email", "Other Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleParent(jTable1);

        Go_Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Go_Back.setIcon(new javax.swing.ImageIcon("C:\\Users\\ankur\\OneDrive\\Documents\\NetBeansProjects\\Connect\\icons\\icons8-left-arrow-50.png")); // NOI18N
        Go_Back.setText("Go Back");
        Go_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_BackActionPerformed(evt);
            }
        });

        supplier_id.setText("Supplier id");

        name.setText("Name");

        address.setText("Address");

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        phone.setText("Phone");

        fax.setText("Fax");

        jt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_emailActionPerformed(evt);
            }
        });

        email.setText("Email");

        jt_other_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_other_detailsActionPerformed(evt);
            }
        });

        other_details.setText("Other Details");
        other_details.setToolTipText("");

        Edit.setText("Edit");
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
        });
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.setEnabled(false);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supplier Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplier_id, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fax)
                    .addComponent(other_details)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(phone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jt_other_details)
                    .addComponent(jt_fax)
                    .addComponent(jt_phone)
                    .addComponent(jt_address)
                    .addComponent(jt_name)
                    .addComponent(jt_sid))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(928, Short.MAX_VALUE)
                .addComponent(Insert)
                .addGap(41, 41, 41)
                .addComponent(Edit)
                .addGap(35, 35, 35)
                .addComponent(Cancel)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Go_Back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Go_Back)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jt_sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jt_other_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(supplier_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(5, 5, 5)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fax)
                                .addGap(15, 15, 15)
                                .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14)
                                .addComponent(other_details, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert)
                    .addComponent(Edit)
                    .addComponent(Cancel))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Go_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go_BackActionPerformed
        // TODO add your handling code here:
        Initialization initialization= new Initialization();
        initialization.setVisible(true);
        dispose();
    }//GEN-LAST:event_Go_BackActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
        if(jt_sid.getText().equals("")|| (jt_name.getText().equals(""))|| (jt_address.getText()).equals("")||
                (jt_phone.getText().equals(""))|| (jt_fax.getText().equals(""))||
                (jt_email.getText()).equals("")){
            JOptionPane.showMessageDialog(this, "Please insert all data");
        }
        else{
            String data[]={jt_name.getText(),jt_address.getText(),jt_phone.getText(),jt_fax.getText(),jt_email.getText(),jt_other_details.getText()};
            
                DefaultTableModel tblmodel=(DefaultTableModel) jTable1.getModel();
                tblmodel.addRow(data);
                JOptionPane.showMessageDialog(this, "Data inserted Successfully");
                 insert_data(jt_sid.getText(),jt_name.getText(),jt_address.getText(),jt_phone.getText(),jt_fax.getText(),jt_email.getText(),jt_other_details.getText());
                jt_sid.setText("");
                jt_name.setText("");
                jt_address.setText("");
                jt_phone.setText(""); 
                jt_fax.setText("");
                jt_email.setText("");
                jt_other_details.setText("");
                 
                 
               
            
        }
    }//GEN-LAST:event_InsertActionPerformed

    private void jt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_emailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jt_emailActionPerformed

    private void jt_other_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_other_detailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_other_detailsActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Inventory;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());
            String sql="Update Supplier set Name=?, Address=?,phone=?, fax=?,email=?,other_details=? where Supplier_id=?";

            PreparedStatement statement = connection.prepareStatement(sql);
          
            statement.setString(1, jt_name.getText());  
            statement.setString(2, jt_address.getText());
            statement.setString(3, jt_phone.getText());
            statement.setString(4, jt_fax.getText());
            statement.setString(5, jt_email.getText());
            statement.setString(6, jt_other_details.getText());
            statement.setString(7, jt_sid.getText());
            statement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            jTable1.clearSelection();
            Insert.setEnabled(true);
               
                
           
//                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
//                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
                jt_sid.setText("");
                jt_name.setText("");
                jt_address.setText("");
                jt_phone.setText(""); 
                jt_fax.setText("");
                jt_email.setText("");
                jt_other_details.setText("");
                DefaultTableModel tblmodel=(DefaultTableModel) jTable1.getModel();
                tblmodel.setRowCount(0);             
                show_supplier();
               
                
              

            
            
              connection.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        
        
    }//GEN-LAST:event_EditActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        Insert.setEnabled(false);
        Cancel.setEnabled(true);
        try{
        DefaultTableModel tblmodel=(DefaultTableModel) jTable1.getModel();
        int selected=jTable1.getSelectedRow();
        jt_sid.setText(tblmodel.getValueAt(selected, 0).toString());
        jt_name.setText(tblmodel.getValueAt(selected, 1).toString());
        jt_address.setText(tblmodel.getValueAt(selected, 2).toString());
        jt_phone.setText(tblmodel.getValueAt(selected, 3).toString());
        jt_fax.setText(tblmodel.getValueAt(selected, 4).toString());
        jt_email.setText(tblmodel.getValueAt(selected, 5).toString());
        jt_other_details.setText(tblmodel.getValueAt(selected, 6).toString());
        }
        catch(NullPointerException e){
        
        jt_other_details.setText("");
        }
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        // TODO add your handling code here:
                jt_sid.setText("");
                jt_name.setText("");
                jt_address.setText("");
                jt_phone.setText(""); 
                jt_fax.setText("");
                jt_email.setText("");
                jt_other_details.setText("");
                jTable1.clearSelection();
                Insert.setEnabled(true);
                
        
    }//GEN-LAST:event_CancelMouseClicked

    /**
     * @param args the command line arguments
     */
   
      public Connection connection;
       public void show_supplier() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Inventory;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("SELECT Supplier_Id, Name, Address, phone,fax, email,Other_details FROM Supplier");

            while (resultSet.next()) {
                String sid=resultSet.getString(1);
                String name = resultSet.getString(2);
                String address = resultSet.getString(3);
                String phone = resultSet.getString(4);
                String fax = resultSet.getString(5);
                String email = resultSet.getString(6);
                String others_des= resultSet.getString(7);
                Addname(name);
                String tbdata[]={sid,name,address,phone,fax,email,others_des};
                
                DefaultTableModel tblmodel=(DefaultTableModel) jTable1.getModel();
                tblmodel.addRow(tbdata);
                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
               
                
              

            }
            
              connection.close();
              for(String name:names){

   System.out.println(name);

}  

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
       
       public void insert_data(String a, String b,String c,String d, String k,String f, String g){
       
          try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Inventory;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());
            String sql="Insert into Supplier (Supplier_id ,Name, Address, phone,fax, email,Other_details ) values(?,?,?,?,?,?,?) ";

            PreparedStatement statement = connection.prepareCall(sql);
//            ResultSet resultSet = statement
//                    .executeQuery("SELECT * FROM Supplier");
            statement.setString(1,a);
            statement.setString(2, b);
            statement.setString(3, c);
            statement.setString(4, d);
            statement.setString(5, k);
            statement.setString(6, f);
            statement.setString(7, g);
            statement.executeUpdate();

            
              connection.close();

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } 
       }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Go_Back;
    private javax.swing.JButton Insert;
    private javax.swing.JLabel address;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jt_address;
    private javax.swing.JTextField jt_email;
    private javax.swing.JTextField jt_fax;
    private javax.swing.JTextField jt_name;
    private javax.swing.JTextField jt_other_details;
    private javax.swing.JTextField jt_phone;
    private javax.swing.JTextField jt_sid;
    private javax.swing.JLabel name;
    private javax.swing.JLabel other_details;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel supplier_id;
    // End of variables declaration//GEN-END:variables



}



